In [1]:
# i0mp if over data on over machine(computer) but we have a link of data they present or avalaible on other platform and we want to 
# fatch when we used this predefined code to acces see
import pandas as pd
import requests
from io import StringIO

url = ""  # copy and paste url here like link 

headers = {"user-agent": "Mzilla/S.0 (Macintosh, Intel Max OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url , headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

In [ ]:
# when we have tsv file like  data.tsv its mean - sepereted value its create problem we used sep= '/t' to give instruction sepreteby this - also

# code
pd.read_csv('movie_titles_matadata.tsv' , sep='/t')

# if over data we dont provide columns name in this situation over pandas make first row as column so in this situation we make column name
# overself by undestanding columns data 

# code 
pd.read_csv('movie.csv', names=['col1 name', 'name 2' , 'name3' ,'etc'])

In [ ]:
# ager hamare data me first row columns name he  he but wah row bangyi he but we select over first row as columns we wtite this code

pd.read_csv('test.csv' , header=1) # write  header= 1

In [ ]:
# if we have 1000 lakh or million data we lod only small data at a time to manage lod and computation we used nrows

# like over data have 100000 row hume hahiye only 1000 row we write

pd.read_csv('data.csv' , nrows=1000)

In [ ]:
# handling Dates data if over data  in string format check by info function we convert it into datatime64 data type we used

pd.read_csv('data.csv' , parse_dates=['date']).info()  # parse_dates to convert pass columns name

# if over dataset 3 columns like one day s3cond motnth etc we want to make one column by combining using this  pass index  parse_dates=['dates': 1,2,3]

In [ ]:
def rename(name):
    if name == 'roayal challenges bangalore':
        return "RCB"
    elif name == 'channi super king': 
        return "csk"
    else:
        name

In [ ]:
# convertors : it we used when over columns in which name are very long i nedd make it short form like example  ipl : team columns  : royal challanges banglurue short form we need
# RCB we apply this

pd.read_csv('data ' , converters={'columns_name':rename})

NameError: name 'rename' is not defined

In [2]:
# Loding a huge dataset in chunks
dfs = pd.read_csv("Housing.csv" ,chunksize=150)

In [ ]:
for chunks in dfs:
    print(chunks)

(150, 13)
(150, 13)
(150, 13)
(95, 13)

In [ ]:
# convert json data in csv format

pd.read_json('train.json')

In [ ]:
# worjing with sql

# pip install mysql.connector

In [5]:
# create connection

conn = mysql.connector.coonect(host='localhost',user='root',password='',database='data_file_name')

NameError: name 'mysql' is not defined

In [ ]:
data = pd.read_sql_query("select * from city(table name)",conn) # it will create for you pandas data frame

# pandas file export

In [ ]:
# to_csv .to_dict , to_excel , to_html , to json

In [14]:
deliveries = pd.read_csv('deliveries.csv')

dfs.head()

          batsman  batsman_runs
0  A Ashish Reddy           280
1      A Chandila             4
2        A Chopra            53
3     A Choudhary            25
4      A Flintoff            62

In [15]:
temp_df = deliveries.groupby('batsman')['batsman_runs'].sum().reset_index()

In [ ]:
temp_df.to_csv("batsam_runs.csv",index=False)

In [9]:
dfs = pd.read_csv("batsam_runs.csv").head()

In [11]:
# to_excel  export over data file in excel file by using this 
temp_df = dfs.groupby('batsman')['batsman_runs'].sum().reset_index()

temp_df.to_excel("batsman_runs.xlsx")

In [16]:
deliveries.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

Empty DataFrame
Columns: [match_id, inning, batting_team, bowling_team, over, ball, batsman, non_striker, bowler, is_super_over, wide_runs, bye_runs, legbye_runs, noball_runs, penalty_runs, batsman_runs, extra_runs, total_runs, player_dismissed, dismissal_kind, fielder]
Index: []

[0 rows x 21 columns]

In [ ]:
# to_html 
dfs.query('batsman_runs == 6').pivot_table(index='over',columns='ball',values='batsman_runs',aggfunc="count").to_html("sixes_heatmap.html")

In [ ]:
# to_json

In [ ]:
# to sql
import pymysql
from sqlalcheny import  create_engine

engine = create_engine("mysql+pymysql://root:@localhost/ipl")
#(root):{password}@{url}/{database}

In [ ]:
# API  aplication programing interface : api is nothing but data piplines -*

import pandas as pd
import requests

2ee72ce30c11bea8f69d4544ab273265 api key

In [ ]:
requests.get('https://api.themoviedb.org/3/movie/top_tated?api_key=2ee72ce30c11bea8f69d4544ab273265e&&1language=en-US&page=1')

ConnectTimeout: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/top_tated?api_key=2ee72ce30c11bea8f69d4544ab273265e&&1language=en-US&page=1 (Caused by ConnectTimeoutError(<HTTPSConnection(host='api.themoviedb.org', port=443) at 0x20888654a50>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))

In [ ]:
import requests
import pandas as pd

API_KEY = "YOUR_API_KEY"

url = f"https://api.themoviedb.org/3/movie/top_rated?api_key=2ee72ce30c11bea8f69d4544ab273265&language=en-US&page=1"

response = requests.get(url)

df =  pd.DataFrame(response.json()['results'])

print(df.head())

ConnectTimeout: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/top_rated?api_key=2ee72ce30c11bea8f69d4544ab273265&language=en-US&page=1 (Caused by ConnectTimeoutError(<HTTPSConnection(host='api.themoviedb.org', port=443) at 0x208886574d0>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))

In [ ]:
import pandas as pd

pd.set_option('display.max_columns', None)   # सभी columns दिखेंगे
pd.set_option('display.width', 1000)         # width बढ़ाओ
pd.set_option('display.max_colwidth', None)  # text कटेगा नहीं

In [ ]:
#df[df['title'].str.contains('Dilwale', case=False, na=False)]

import requests
import pandas as pd

API_KEY = "YOUR_API_KEY"

all_movies = []

for page in range(1, 4):  # 428 pages
    url = f"https://api.themoviedb.org/3/movie/top_rated?api_key=2ee72ce30c11bea8f69d4544ab273265&language=en-US&page=1"
    
    response = requests.get(url)
    data = response.json()
    
    all_movies.extend(data['results'])

# DataFrame बनाओ
df = pd.DataFrame(all_movies)

#print("Total rows:", len(df))
#print(df[['title', 'vote_average']].head())

ConnectTimeout: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/top_rated?api_key=2ee72ce30c11bea8f69d4544ab273265&language=en-US&page=1 (Caused by ConnectTimeoutError(<HTTPSConnection(host='api.themoviedb.org', port=443) at 0x20888656490>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))

In [ ]:
# use rapid api and find dataset in csv format by using this and uplod on kaggle